config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  root to: "guests#index"
  resources :guests do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'lookup'
    end
  end

  resources :baths, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :drinks, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :foods, only: [:index] 

end

app/models/guest.rb
class Guest < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender
  belongs_to_active_hash :visit1
  belongs_to_active_hash :visit2
  belongs_to_active_hash :adl

  has_one_attached :image
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :histories, dependent: :destroy
  has_one    :bath, dependent: :destroy
  has_one    :drink, dependent: :destroy
  has_one    :food, dependent: :destroy

  # name,remarksというエイリアスをつける
  ransack_alias :name, :first_name_or_last_name_or_first_name_kana_or_last_name_kana
  ransack_alias :remarks, :description_or_bath_remark_bath_or_drink_remark_drink_or_food_remark_food

  validates :description, length: { maximum: 1000 }
  with_options presence: true do
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'full-width characters.' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'full-width characters.' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'full-width katakana characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'full-width katakana characters.' }
    validates :gender_id
    validates :visit1_id
    validates :visit2_id
    validates :adl_id
    with_options numericality: { other_than: 0, message: "can't be blank" } do
      validates :gender_id
      validates :visit1_id
      validates :adl_id
    end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :destroy, :edit, :update]
  before_action :move_to_index, except: :index
  before_action :move_to_index_non_editor, only: [:edit, :show]
  before_action :lookup_guest, only: [:index, :lookup]

  def index
    if user_signed_in?
      @guests = @p.result.includes([:bath, :drink, :food])
      @count = @guests.size
    end
  end

  def lookup
    @guests = @p.result.includes([:bath, :drink, :food]) # 検索条件にマッチした利用者の情報を取得
    @count = @guests.size
  end

  def new
    @guestdata = GuestData.new
  end

  def create
    @guestdata = GuestData.new(guest_params)
    if @guestdata.valid?
      @guestdata.save
      flash[:success] = '利用者情報を登録しました'
      redirect_to root_path
    else
      render('guests/new')
    end
  end

  def destroy
    if @guest.destroy
      flash[:danger] = '利用者情報を削除しました'
      redirect_to root_path
    else
      redirect_to guest_path(@guest.id)
    end
  end

  def edit
    session[:bath_day] = params[:bath_day] if params[:bath_day].present?
    session[:drink_day] = params[:drink_day] if params[:drink_day].present?
    session[:food_day] = params[:food_day] if params[:food_day].present?
    @guestdata = GuestData.new(
      first_name: @guest.first_name,
      last_name: @guest.last_name,
      first_name_kana: @guest.first_name_kana,
      last_name_kana: @guest.last_name_kana,
      gender_id: @guest.gender_id,
      visit1_id: @guest.visit1_id,
      visit2_id: @guest.visit2_id,
      adl_id: @guest.adl_id,
      description: @guest.description,
      bathing_id: @guest.bath.bathing_id,
      infection_id: @guest.bath.infection_id,
      timing_id: @guest.bath.timing_id,
      remark_bath: @guest.bath.remark_bath,
      drink_type_id: @guest.drink.drink_type_id,
      warm: @guest.drink.warm,
      thickness_id: @guest.drink.thickness_id,
      diabetes: @guest.drink.diabetes,
      remark_drink: @guest.drink.remark_drink,
      staple_type_id: @guest.food.staple_type_id,
      staple_amount_id: @guest.food.staple_amount_id,
      main_dish_type_id: @guest.food.main_dish_type_id,
      main_dish_amount_id: @guest.food.main_dish_amount_id,
      side_dish_type_id: @guest.food.side_dish_type_id,
      side_dish_amount_id: @guest.food.side_dish_amount_id,
      low_salt: @guest.food.low_salt,
      soup_thick: @guest.food.soup_thick,
      denture_id: @guest.food.denture_id,
      remark_food: @guest.food.remark_food,
      forbid_food: @guest.food.forbids.pluck(:forbid_food).join(',')
    )
  end

  def update
    @guestdata = GuestData.new(guest_params)
    if @guestdata.valid?
      @guestdata.update
      if guest_params[:image].present?
        @guest.update(image: guest_params[:image]) if @guest.valid?
      end
      flash[:info] = '利用者情報を更新しました'
      if session[:bath_day].present?
        if session[:bath_day] == '0'
          redirect_to baths_path
        else
          redirect_to search_bath_path(session[:bath_day])
        end
        session[:bath_day].clear
      elsif session[:drink_day].present?
        if session[:drink_day] == '0'
          redirect_to drinks_path
        else
          redirect_to search_drink_path(session[:drink_day])
        end
        session[:drink_day].clear
      elsif session[:food_day].present?
        if session[:food_day] == '0'
          redirect_to foods_path
        else
          redirect_to foods_path(q: { g: {'1': {m: 'or', visit1_id_eq: session[:food_day], visit2_id_eq: session[:food_day]}, '0': {user_id_eq: current_user.id.to_s}} })
        end
        session[:food_day].clear
      else
        redirect_to action: :show
      end
    else
      render('guests/edit')
    end
  end

  def show
    @comment_new = Comment.new
    @comments = Comment.joins(:guest).where(guests: { id: @guest.id }).order('created_at ASC')
    @histories = History.joins(:guest).where(guests: { id: @guest.id }).order('created_at ASC')
  end

  private

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def guest_params
    params.require(:guest_data).permit(
      :first_name, :last_name, :first_name_kana, :last_name_kana, :gender_id, :visit1_id, :visit2_id, :description, :adl_id,
      :bathing_id, :infection_id, :timing_id, :remark_bath,
      :drink_type_id, :warm, :thickness_id, :diabetes, :remark_drink,
      :log, :log_type_id,
      :image,
      :staple_type_id, :staple_amount_id, :main_dish_type_id, :main_dish_amount_id, :side_dish_type_id, :side_dish_amount_id,
      :low_salt, :soup_thick, :denture_id, :remark_food,
      :forbid_food
    ).merge(id: params[:id], user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      flash[:warning] = 'ログインしたユーザーでないと利用が認められていません'
      redirect_to root_path
    end
  end

  def move_to_index_non_editor
    unless current_user.id == @guest.user.id
      flash[:warning] = '利用者情報を登録したユーザーでないと閲覧が認められていません'
      redirect_to root_path
    end
  end

  def lookup_guest
    @p = Guest.ransack(params[:q]) # 検索オブジェクトを生成
    if user_signed_in?
      @p.user_id_eq = current_user.id # デフォルトでユーザーが管理する利用者のみを表示
    end
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/show.html.erb
<div class="container my-3">
  <h1 class="text-center m-3"><%= "#{@guest.first_name} #{@guest.last_name}さんの詳細" %></h1>
  <%# 利用者の詳細テーブル %>
  <div class="container">
    <div class="text-center my-3">
    <% if @guest.image.attached? %>
      <%= image_tag @guest.image.variant(resize_to_fit: [256, 256]), class: 'guest-image rounded img-thumbnail', alt: '顔写真' %>
    <% else %>
    <% end %>
    </div>
    <table class="table table-bordered">
      <caption>利用者の詳細</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">名前</th>
          <th scope="col">性別</th>
          <th scope="col">利用日１</th>
          <th scope="col">利用日２</th>
          <th scope="col">歩行状態</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="col"><%= "#{@guest.first_name} #{@guest.last_name} (#{@guest.first_name_kana} #{@guest.last_name_kana})" %></td>
          <td scope="col"><%= @guest.gender.name %></td>
          <td scope="col"><%= @guest.visit1.name %></td>
          <td scope="col"><%= @guest.visit2.name %></td>
          <td scope="col"><%= @guest.adl.name %></td>
        </tr>
      </tbody>
      <thead class="thead-dark">
        <tr>
          <th colspan="12">利用者の備考</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="12"><%= @guest.description %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /利用者の詳細テーブル %>
  <%# 利用者の入浴詳細テーブル %>
  <div class="container">
    <table class="table table-bordered">
      <caption>入浴の詳細</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">入浴形態</th>
          <th scope="col">感染症</th>
          <th scope="col">入浴の順番</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="col"><%= @guest.bath.bathing.name %></td>
          <td scope="col"><%= @guest.bath.infection.name %></td>
          <td scope="col"><%= @guest.bath.timing.name %></td>
        </tr>
      </tbody>
      <thead class="thead-dark">
        <tr>
          <th colspan="12">入浴の備考</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="12"><%= @guest.bath.remark_bath %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /利用者の入浴詳細テーブル %>
  <%# 利用者の水分詳細テーブル %>
  <div class="container">
    <table class="table table-bordered">
      <caption>水分の詳細</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">飲み物の種類</th>
          <th scope="col">とろみの量</th>
          <th scope="col">温めの有無</th>
          <th scope="col">糖尿病の有無</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="col"><%= @guest.drink.drink_type.name %></td>
          <td scope="col"><%= @guest.drink.thickness.name %></td>
          <td scope="col"><%= @guest.drink.warm ? "温める" : "温めない"  %></td>
          <td scope="col"><%= @guest.drink.diabetes ? "あり" : "なし"  %></td>
        </tr>
      </tbody>
      <thead class="thead-dark">
        <tr>
          <th colspan="12">水分の備考</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="12"><%= @guest.drink.remark_drink %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /利用者の水分詳細テーブル %>
  <%# 利用者の食事詳細テーブル %>
  <div class="container">
    <table class="table table-bordered">
      <caption>食事の詳細</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">主食の形態</th>
          <th scope="col">主菜の形態</th>
          <th scope="col">副菜の形態</th>
          <th scope="col" colspan="3">禁止食材</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="col"><%= @guest.food.staple_type.name %></td>
          <td scope="col"><%= @guest.food.main_dish_type.name %></td>
          <td scope="col"><%= @guest.food.side_dish_type.name %></td>
          <td scope="col" colspan="3"><% @guest.food.forbids.each do |x| %>
            <%= x.forbid_food %>
          <% end %></td>
        </tr>
      </tbody>
      <thead class="thead-dark">
        <tr>
          <th scope="col">主食の量</th>
          <th scope="col">主菜の量</th>
          <th scope="col">副菜の量</th>
          <th scope="col">義歯</th>
          <th scope="col">汁物のとろみ</th>
          <th scope="col">塩分制限</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="col"><%= @guest.food.staple_amount.name %></td>
          <td scope="col"><%= @guest.food.main_dish_amount.name %></td>
          <td scope="col"><%= @guest.food.side_dish_amount.name %></td>
          <td scope="col"><%= @guest.food.denture.name %></td>
          <td scope="col"><%= @guest.food.soup_thick ? "あり" : "なし" %></td>
          <td scope="col" ><%= @guest.food.low_salt ? "あり" : "なし" %></td>
        </tr>
      </tbody>
      <thead class="thead-dark">
        <tr>
          <th colspan="12">食事の備考</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="12"><%= @guest.food.remark_food %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /利用者の食事詳細テーブル %>
  <%# 利用者の更新履歴テーブル %>
  <div class="container">
    <table class="table table-bordered">
      <caption>更新履歴</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">理由</th>
          <th scope="col">更新内容</th>
          <th scope="col">日付</th>
        </tr>
      </thead>
      <tbody>
        <% @histories.each do |history| %>
          <tr>
            <td scope="col" style="width:30%"><%= history.log_type.name %></td>
            <td scope="col" style="width:50%"><%= history.log %></td>
            <td scope="col" style="width:20%"><%= history.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%# /利用者の更新履歴テーブル %>
  <%# 利用者のコメントテーブル %>
  <div class="container">
    <table class="table table-bordered">
      <caption>コメント</caption>
      <thead class="thead-dark">
        <tr>
          <th scope="col">日付</th>
          <th scope="col">本文</th>
          <th scope="col">編集/削除</th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td scope="col" style="width:20%"><%= comment.created_at.strftime('%Y/%m/%d') %></td>
            <td scope="col" style="width:55%"><%= comment.text %></td>
            <td scope="col" style="width:25%">

              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#commentEdit-<%= "#{comment.id}" %>" id="edit-start-<%= "#{comment.id}" %>">
                編集
              </button>

              <!-- Modal -->
              <div class="modal fade" id="commentEdit-<%= "#{comment.id}" %>" tabindex="-1" role="dialog" aria-labelledby="commentEdit-<%= "#{comment.id}" %>Title" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="commentEdit-<%= "#{comment.id}" %>Title">コメント編集フォーム</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= form_with(model: comment, url: "/guests/#{comment.guest_id}/comments/#{comment.id}", method: :patch, local: true) do |f| %>
                        <div class="form-row my-3">
                          <div class="form-group col-sm-12">
                            <label for="edit-text">本文<span class="text-danger pl-3">必須</span></label>
                            <%= f.text_area :text, class:"form-control", id:"edit-text" %>
                          </div>
                        </div>
                        <%# 登録ボタン %>
                        <div class="form-row my-3">
                          <div class="form-group col-sm-12 modal-footer">
                            <%= f.submit "コメントを編集する" ,class:"btn btn-primary", role: "button" %>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">編集を中止する</button>
                          </div>
                        </div>
                        <%# /登録ボタン %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Modal -->
              <%= link_to '削除', guest_comment_path(comment.guest.id, comment.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger", role: "button" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%# /利用者のコメントテーブル %>
  <%# 編集あるいは削除ボタン %>
  <div class="row">
      <div class="col">
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-success btn-block btn-lg" data-toggle="modal" data-target="#commentNew">
                <i class="far fa-comment-dots"></i> コメントをする
              </button>

              <!-- Modal -->
              <div class="modal fade" id="commentNew" tabindex="-1" role="dialog" aria-labelledby="commentNewTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="commentNewTitle">コメントフォーム</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= form_with(model: [@guest, @comment_new], local: true) do |f| %>
                        <div class="form-row my-3">
                          <div class="form-group col-sm-12">
                            <label for="text">本文<span class="text-danger pl-3">必須</span></label>
                            <%= f.text_area :text, class:"form-control", id:"text" %>
                          </div>
                        </div>
                        <%# 登録ボタン %>
                        <div class="form-row my-3">
                          <div class="form-group col-sm-12 modal-footer">
                            <%= f.submit "コメントをする" ,class:"btn btn-primary", role: "button" %>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">中止する</button>
                          </div>
                        </div>
                        <%# /登録ボタン %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Modal -->
    </div>
    <div class="col">
      <%= link_to edit_guest_path(edit_jump(@guest.id)), method: :get, class: "btn btn-primary btn-block btn-lg", role: "button" do %>
      <i class="fas fa-edit"></i> 編集
      <% end %>
    </div>
    <div class="col">
      <%= link_to guest_path(@guest.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-block btn-lg", role: "button" do %>
      <i class="far fa-trash-alt"></i> 削除
      <% end %>
    </div>
  </div>
  <%# /編集あるいは削除ボタン %>
</div>