config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  root to: "guests#index"
  resources :guests do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'lookup'
    end
  end

  resources :baths, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :drinks, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :foods, only: [:index] 

end

app/models/drink.rb
class Drink < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :thickness
  belongs_to_active_hash :drink_type

  belongs_to :guest

  # # boolean型のチェック
  validates :warm, inclusion: { in: [true, false] }
  validates :diabetes, inclusion: { in: [true, false] }
  # 文字数のチェック
  validates :remark_drink, length: { maximum: 20 }

  with_options presence: true do
    validates :drink_type_id
    validates :thickness_id
    with_options numericality: { other_than: 0, message: 'の選択肢を選んでください' } do
      validates :drink_type_id
      validates :thickness_id
    end
  end
end

app/models/drink_type.rb
class DrinkType < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '牛乳' },
    { id: 2, name: 'コーヒー牛乳' },
    { id: 3, name: 'ヤクルト' },
    { id: 4, name: 'ジュース' },
    { id: 5, name: 'プリン' },
    { id: 6, name: 'ヨーグルト' },
    { id: 7, name: '牛乳ゼリー' },
    { id: 8, name: 'お茶' }
  ]
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_day_of_the_week, only: :search
  before_action :move_to_index

  def index
    # 牛乳
    @milk_guests = SearchGuestsService.search_drink(current_user.id, 1)
    # コーヒー牛乳
    @coffee_milk_guests = SearchGuestsService.search_drink(current_user.id, 2)
    # ヤクルト
    @yakult_guests = SearchGuestsService.search_drink(current_user.id, 3)
    # ジュース
    @juice_guests = SearchGuestsService.search_drink(current_user.id, 4)
    # プリン
    @pudding_guests = SearchGuestsService.search_drink(current_user.id, 5)
    # ヨーグルト
    @yogurt_guests = SearchGuestsService.search_drink(current_user.id, 6)
    # 牛乳ゼリー
    @milk_jelly_guests = SearchGuestsService.search_drink(current_user.id, 7)
    # お茶
    @tea_guests = SearchGuestsService.search_drink(current_user.id, 8)
    @guests = Guest.includes(:user, :drink).where(users: { id: current_user.id })
    @count = @guests.size
  end

  def search
    # 牛乳
    @milk_guests = SearchGuestsService.search_drink_day(current_user.id, 1, @day)
    # コーヒー牛乳
    @coffee_milk_guests = SearchGuestsService.search_drink_day(current_user.id, 2, @day)
    # ヤクルト
    @yakult_guests = SearchGuestsService.search_drink_day(current_user.id, 3, @day)
    # ジュース
    @juice_guests = SearchGuestsService.search_drink_day(current_user.id, 4, @day)
    # プリン
    @pudding_guests = SearchGuestsService.search_drink_day(current_user.id, 5, @day)
    # ヨーグルト
    @yogurt_guests = SearchGuestsService.search_drink_day(current_user.id, 6, @day)
    # 牛乳ゼリー
    @milk_jelly_guests = SearchGuestsService.search_drink_day(current_user.id, 7, @day)
    # お茶
    @tea_guests = SearchGuestsService.search_drink_day(current_user.id, 8, @day)
    # 曜日情報を入力
    day_of_the_week = %w[全 月 火 水 木 金 土 日]
    today = @day.to_i
    @day_of_the_week = day_of_the_week[today]
    # 利用者数を集計
    count = 0
    count += @milk_guests.size
    count += @coffee_milk_guests.size
    count += @yakult_guests.size
    count += @juice_guests.size
    count += @pudding_guests.size
    count += @yogurt_guests.size
    count += @milk_jelly_guests.size
    count += @tea_guests.size
    @count = count
    render action: :index
  end

  private

  def move_to_index
    unless user_signed_in?
      flash[:warning] = 'ログインしたユーザーでないと利用が認められていません'
      redirect_to root_path
    end
  end

  def set_day_of_the_week
    @day = params[:id]
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/index.html.erb
<%# 曜日ボタン %>
<div class="container d-flex justify-content-center my-3">
  <div class="btn-group" role="group" aria-label="Day-of-the-week">
    <%= link_to '全表示', drinks_path, class: "btn btn-outline-info nav-link", id: "allday", role: "button" %>
    <%= link_to '月曜日', search_drink_path(1), class: "btn btn-outline-info nav-link", id: "monday", role: "button" %>
    <%= link_to '火曜日', search_drink_path(2), class: "btn btn-outline-info nav-link", id: "tuesday", role: "button" %>
    <%= link_to '水曜日', search_drink_path(3), class: "btn btn-outline-info nav-link", id: "wednesday", role: "button" %>
    <%= link_to '木曜日', search_drink_path(4), class: "btn btn-outline-info nav-link", id: "thursday", role: "button" %>
    <%= link_to '金曜日', search_drink_path(5), class: "btn btn-outline-info nav-link", id: "friday", role: "button" %>
    <%= link_to '土曜日', search_drink_path(6), class: "btn btn-outline-info nav-link", id: "saturday", role: "button" %>
    <%= link_to '日曜日', search_drink_path(7), class: "btn btn-outline-info nav-link", id: "sunday", role: "button" %>
  </div>
</div>
 <%# /曜日ボタン %>
<div class="container-fluid">
  <%# タイトル %>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h1 class="text-center">水分提供表</h1>
      </div>
    </div>
    <div class="mb-3 d-flex justify-content-end">
      <button type="button" class="btn btn-success print printing"><i class="fas fa-print" aria-hidden="true"></i>この表を印刷する</button> 
    </div>
    <div class="row mb-3">
      <div class="col-4 text-left">
        <h3><%= @day_of_the_week  ? "#{@day_of_the_week}曜日" : "全表示" %></h3>
      </div>
      <div class="col-8 text-right">
       <h3><%= "利用予定者　#{@count}名" if @count %></h3>
      </div>
    </div>
  </div>
  <%# /タイトル %>

  <%# 牛乳とコーヒー牛乳 %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">牛乳</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @milk_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">コーヒー牛乳</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @coffee_milk_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /牛乳とコーヒー牛乳 %>

  <%# ヤクルトとジュース %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">ヤクルト</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @yakult_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">ジュース</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @juice_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /ヤクルトとジュース %>

  <%# プリンとヨーグルト %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">プリン</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @pudding_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">ヨーグルト</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @yogurt_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /プリンとヨーグルト %>

  <%# 牛乳ゼリーとお茶 %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">牛乳ゼリー</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @milk_jelly_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">お茶</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">水分の備考</th>
              <th scope="col">とろみ</th>
              <th scope="col">温</th>
              <th scope="col">DM</th>
            </tr>
          </thead>
          <tbody>
            <% @tea_guests.each do |guest| %>
              <%= render partial: "shared/drink", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /牛乳ゼリーとお茶 %>

</div>
<%= javascript_pack_tag 'nav-active' %>