config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  root to: "guests#index"
  resources :guests do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'lookup'
    end
  end

  resources :baths, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :drinks, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :foods, only: [:index] 

end

app/models/bath.rb
class Bath < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :bathing
  belongs_to_active_hash :infection
  belongs_to_active_hash :timing

  belongs_to :guest

  validates :remark_bath, length: { maximum: 20 }
  with_options presence: true do
    validates :bathing_id
    validates :infection_id
    validates :timing_id
    with_options numericality: { other_than: 0, message: 'の選択肢を選んでください' } do
      validates :bathing_id
      validates :infection_id
    end
  end
end

app/controllers/baths_controller.rb
class BathsController < ApplicationController
  before_action :set_day_of_the_week, only: :search
  before_action :move_to_index

  def index
    # user/男子/一般浴
    @normal_males = SearchGuestsService.search_bath(current_user.id, 1, 1)
    # user/女子/一般浴
    @normal_females = SearchGuestsService.search_bath(current_user.id, 2, 1)
    # user/男子/一般チェアー浴
    @normal_chair_males = SearchGuestsService.search_bath(current_user.id, 1, 2)
    # user/女子/一般チェアー浴
    @normal_chair_females = SearchGuestsService.search_bath(current_user.id, 2, 2)
    # user/男子/チェアー浴
    @chair_males = SearchGuestsService.search_bath(current_user.id, 1, 3)
    # user/女子/チェアー浴
    @chair_females = SearchGuestsService.search_bath(current_user.id, 2, 3)
    @guests = Guest.includes(:user, :bath).where(users: { id: current_user.id })
    @count = @guests.size
  end

  def search
    # user/男子/一般浴
    @normal_males = SearchGuestsService.search_bath_day(current_user.id, 1, 1, @day)
    # user/女子/一般浴
    @normal_females = SearchGuestsService.search_bath_day(current_user.id, 2, 1, @day)
    # user/男子/一般チェアー浴
    @normal_chair_males = SearchGuestsService.search_bath_day(current_user.id, 1, 2, @day)
    # user/女子/一般チェアー浴
    @normal_chair_females = SearchGuestsService.search_bath_day(current_user.id, 2, 2, @day)
    # user/男子/チェアー浴
    @chair_males = SearchGuestsService.search_bath_day(current_user.id, 1, 3, @day)
    # user/女子/チェアー浴
    @chair_females = SearchGuestsService.search_bath_day(current_user.id, 2, 3, @day)
    # 曜日情報を入力
    day_of_the_week = %w[全 月 火 水 木 金 土 日]
    today = @day.to_i
    @day_of_the_week = day_of_the_week[today]
    # 利用者数を集計
    count = 0
    count += @normal_males.size
    count += @normal_females.size
    count += @normal_chair_males.size
    count += @normal_chair_females.size
    count += @chair_males.size
    count += @chair_females.size
    @count = count
    render action: :index
  end

  private

  def move_to_index
    unless user_signed_in?
      flash[:warning] = 'ログインしたユーザーでないと利用が認められていません'
      redirect_to root_path
    end
  end

  def set_day_of_the_week
    @day = params[:id]
  end
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/views/baths/index.html.erb
<%# 曜日ボタン %>
<div class="container d-flex justify-content-center my-3">
  <div class="btn-group" role="group" aria-label="Day-of-the-week">
    <%= link_to '全表示', baths_path, class: "btn btn-outline-info nav-link", id: "allday", role: "button" %>
    <%= link_to '月曜日', search_bath_path(1), class: "btn btn-outline-info nav-link", id: "monday", role: "button" %>
    <%= link_to '火曜日', search_bath_path(2), class: "btn btn-outline-info nav-link", id: "tuesday", role: "button" %>
    <%= link_to '水曜日', search_bath_path(3), class: "btn btn-outline-info nav-link", id: "wednesday", role: "button" %>
    <%= link_to '木曜日', search_bath_path(4), class: "btn btn-outline-info nav-link", id: "thursday", role: "button" %>
    <%= link_to '金曜日', search_bath_path(5), class: "btn btn-outline-info nav-link", id: "friday", role: "button" %>
    <%= link_to '土曜日', search_bath_path(6), class: "btn btn-outline-info nav-link", id: "saturday", role: "button" %>
    <%= link_to '日曜日', search_bath_path(7), class: "btn btn-outline-info nav-link", id: "sunday", role: "button" %>
  </div>
</div>
 <%# /曜日ボタン %>
<div class="container-fluid">
  <%# タイトル %>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h1 class="text-center">入浴形態表</h1>
      </div>
    </div>
    <div class="mb-3 d-flex justify-content-end">
      <button type="button" class="btn btn-success print printing"><i class="fas fa-print" aria-hidden="true"></i>この表を印刷する</button> 
    </div>
    <div class="row mb-3">
      <div class="col-4 text-left">
        <h3><%= @day_of_the_week  ? "#{@day_of_the_week}曜日" : "全表示" %></h3>
      </div>
      <div class="col-8 text-right">
       <h3><%= "利用予定者　#{@count}名" if @count %></h3>
      </div>
    </div>
  </div>
  <%# /タイトル %>

  <%# 一般浴 %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">一般浴 男子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @normal_males.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">一般浴 女子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @normal_females.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /一般浴 %>


  <%# 一般チェア浴 %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">一般チェアー浴 男子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @normal_chair_males.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">一般チェアー浴 女子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @normal_chair_females.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /一般チェア浴 %>


  <%# チェア浴 %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">チェアー浴 男子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @chair_males.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xl-6">
        <h3 class="text-center bg-info text-white">チェアー浴 女子</h3>
        <table class="table table-striped table-bordered table-hover table-clickable">
          <thead class="thead-dark">
            <tr>
              <th scope="col"></th>
              <th scope="col">名前</th>
              <th scope="col">入浴の備考</th>
              <th scope="col">順番</th>
              <th scope="col">感染症</th>
            </tr>
          </thead>
          <tbody>
            <% @chair_females.each do |guest| %>
              <%= render partial: "shared/bath", locals: { guest: guest } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%# /チェア浴 %>
  

</div>
<%= javascript_pack_tag 'nav-active' %>