config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  root to: "guests#index"
  resources :guests do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'lookup'
    end
  end

  resources :baths, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :drinks, only: [:index] do
    member do
      get 'search'
    end
  end

  resources :foods, only: [:index] 

end

app/views/shared/_bath.html.erb
<tr class="guest-no-<%= guest.id %>" data-href="<%= edit_guest_path(guest.id, bath_day: edit_jump(params[:id])) %>" >
  <td scope="col" style="width:5%"></td>
  <td scope="col" style="width:30%"><%= "#{guest.first_name} #{guest.last_name}" %></td>
  <td scope="col" style="width:25%"><%= guest.bath.remark_bath %></td>
  <td scope="col" style="width:15%"><%= guest.bath.timing.name %></td>
  <td scope="col" style="width:25%"><%= guest.bath.infection_id == 1 ? "" : "#{guest.bath.infection.name}" %></td>
</tr>

app/views/shared/_drink.html.erb
<tr class="guest-no-<%= guest.id %>" data-href="<%= edit_guest_path(guest.id, drink_day: edit_jump(params[:id])) %>" >
  <td scope="col" style="width:5%"></td>
  <td scope="col" style="width:30%"><%= "#{guest.first_name} #{guest.last_name}" %></td>
  <td scope="col" style="width:30%"><%= guest.drink.remark_drink %></td>
  <td scope="col" style="width:25%"><%= guest.drink.thickness_id == 1 ? "" : "#{guest.drink.thickness.name}" %></td>
  <td scope="col" style="width:5%"><%= guest.drink.warm ? "●" : "" %></td>
  <td scope="col" style="width:5%"><%= guest.drink.diabetes ? "●" : "" %></td>
</tr>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='text-danger error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_food.html.erb
<tr class="guest-no-<%= food.guest_id %>" data-href="<%= edit_guest_path(food.guest_id, food_day: edit_jump(get_url())) %>" >
  <td scope="col"><%= "#{food.guest.first_name} #{food.guest.last_name}" %></td>
  <td scope="col"><%= food.staple_type.name %>/<%= food.staple_amount.name %></td>
  <td scope="col"><%= food.main_dish_type.name %>/<%= food.main_dish_amount.name %></td>
  <td scope="col"><%= food.side_dish_type.name %>/<%= food.side_dish_amount.name %></td>
  <td scope="col"><% food.forbids.each do |x| %>
  <%= x.forbid_food %>
  <% end %></td>
  <td scope="col"><%= food.denture.name %></td>
  <td scope="col" class="text-center"><%= food.low_salt ? "●" : "" %></td>
  <td scope="col" class="text-center"><%= food.soup_thick ? "●" : "" %></td>
  <td scope="col"><%= food.remark_food %></td>
</tr>

app/views/shared/_guest.html.erb
<tr class="guest-list guest-no-<%= guest.id %>">
  <td scope="col"><%= "#{guest.first_name} #{guest.last_name}" %></td>
  <td scope="col"><%= guest.gender.name %></td>
  <td scope="col"><%= guest.visit1.name %></td>
  <td scope="col"><%= guest.visit2.name %></td>
  <td scope="col"><%= guest.adl.name %></td>
  <td scope="col"><%= guest.bath.bathing.name %></td>
  <td scope="col"><%= guest.drink.drink_type.name %></td>
  <td scope="col"><%= guest.food.staple_type.name %></td>
  <td scope="col" class="print">
    <%= link_to '詳細', guest_path(guest.id), method: :get, class: "btn btn-success", role: "button" %>
    <%= link_to '編集', edit_guest_path(edit_jump(guest.id)), method: :get, class: "btn btn-primary", role: "button" %>
    <%= link_to '削除', guest_path(guest.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger", role: "button" %>
  </td>
</tr>

app/views/shared/_header.html.erb
<header class="header bg-light">
  <nav class="navbar navbar-expand-xl navbar-white bg-light">

    <%# ブランドロゴ表示 %>
    <div>
      <%= link_to '兵声援', root_path, class: "navbar-brand text-dark" %>
    </div>
    <% if user_signed_in? %>
      <div>
        <span class="navbar-brand text-dark"><%= "ようこそ #{current_user.name}さん" %></span>
      </div>
    <% end %>
    <%# トグル %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <%# メニューバー %>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">

          </li>
          <li class="nav-item">
            <%= link_to new_guest_path, class: "btn btn-outline-dark nav-link", id: "entry", role: "button"  do %>
            <i class="fas fa-user-plus"></i>利用者を登録する
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to root_path, class: "btn btn-outline-dark nav-link", id: "guest-index", role: "button" do %>
            <i class="fas fa-users"></i>利用者一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to lookup_guests_path, class: "btn btn-outline-dark nav-link", id: "lookup-index", role: "button" do %>
            <i class="fas fa-search"></i>詳細検索
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to baths_path, class: "btn btn-outline-dark nav-link", id: "bath-index", role: "button" do %>
            <i class="fas fa-bath"></i>入浴形態表
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to drinks_path, class: "btn btn-outline-dark nav-link", id: "drink-index", role: "button" do %>
            <i class="fas fa-coffee"></i>水分提供表
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to foods_path, class: "btn btn-outline-dark nav-link", id: "food-index", role: "button" do %>
            <i class="fas fa-utensils"></i>食事提供表
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-outline-dark nav-link", role: "button" do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "btn btn-outline-dark nav-link", role: "button" do %>
            <i class="fas fa-user-circle"></i>新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "btn btn-outline-dark nav-link", role: "button" do %>
            <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_guest_sign_in_path, method: :post, class: "btn btn-outline-dark nav-link", role: "button" do %>
            <i class="fas fa-sign-in-alt"></i>テストログイン(閲覧用)
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>

app/views/shared/_lookup.html.erb
<tr class="guest-list guest-no-<%= guest.id %>" data-href="<%= guest_path(guest.id) %>" >
  <td scope="col"><%= "#{guest.first_name} #{guest.last_name}" %></td>
  <td scope="col"><%= guest.gender.name %></td>
  <td scope="col"><%= guest.visit1.name %>/<%= guest.visit2.name %></td>
  <td scope="col"><%= guest.adl.name %></td>

  <td scope="col"><%= guest.bath.bathing.name %></td>
  <td scope="col"><%= guest.bath.infection.name %></td>

  <td scope="col"><%= guest.drink.drink_type.name %></td>
  <td scope="col"><%= guest.drink.thickness.name %></td>
  <td scope="col"><%= guest.drink.warm ? "●" : "" %></td>
  <td scope="col"><%= guest.drink.diabetes ? "●" : ""  %></td>

  <td scope="col"><%= guest.food.staple_type.name %></td>
  <td scope="col"><%= guest.food.main_dish_type.name %></td>
  <td scope="col"><%= guest.food.side_dish_type.name %></td>
  <td scope="col"><%= guest.food.denture.name %></td>
  <td scope="col" class="text-center"><%= guest.food.low_salt ? "●" : "" %></td>
  <td scope="col" class="text-center"><%= guest.food.soup_thick ? "●" : "" %></td>

</tr>